### ISSUE TITLE
Images are too big. Takes long time to load.

### ISSUE THREAD

**Issue by sanjuruk** [Monitoring6/monitoring6.github.io#3]
All pictures must be less than 200KB. The standard size of pictures allowed for a website is 125KB.

Reduce size of
- All 3 M6 culture images: Crop and reduce the resolution
- Vision page background image: Reduce the resolution(Standard full-screen background should be 2000pixels wide)

Delete unnecessary images which are not being used.

**Comment by kangyeon0728** [comment]
did it

**Comment by sanjuruk** [comment]
Changes are not active on the published breach yet
